PREP(additionalItemsAddItems);
PREP(additionalItemsCategory);
PREP(createRole);
PREP(deleteRole);
PREP(initFramework);
PREP(refreshEditRolesGUI);
PREP(saveRole);
PREP(scanConfig);
PREP(spawnEditRoles);
