#include "script_component.hpp"

ADDON = false;

// Addon Settings:

// define for SPATIALIZATION_SETTING in radio\script_component#22
SPATIALIZATION_SETTINGS(ACRE_PRC343,"AN/PRC-343");
SPATIALIZATION_SETTINGS(ACRE_PRC152,"AN/PRC-152");
SPATIALIZATION_SETTINGS(ACRE_PRC148,"AN/PRC-148");
SPATIALIZATION_SETTINGS(ACRE_PRC117F,"AN/PRC-117F");
SPATIALIZATION_SETTINGS(ACRE_PRC77,"AN/PRC-77");
SPATIALIZATION_SETTINGS(ACRE_SEM52SL,"SEM 52 SL");
SPATIALIZATION_SETTINGS(ACRE_SEM70,"SEM 70");
SPATIALIZATION_SETTINGS(ACRE_BF888S,"BF-888S");
SPATIALIZATION_SETTINGS(ACRE_VRC64,"AN/VRC-64");
SPATIALIZATION_SETTINGS(ACRE_VRC103,"AN/VRC-103");
SPATIALIZATION_SETTINGS(ACRE_VRC110,"AN/VRC-110");
SPATIALIZATION_SETTINGS(ACRE_VRC111,"AN/VRC-111");
SPATIALIZATION_SETTINGS(ACRE_SEM90,"SEM90");

#include "XEH_PREP.hpp"

ADDON = true;
