#include "script_component.hpp"

ADDON = false;

#include "XEH_PREP.hpp"

// Addon Settings:

// define for SPATIALIZATION_SETTING in radio\script_component#22
SPATIALIZATION_SETTINGS(PRC343,"AN/PRC-343");
SPATIALIZATION_SETTINGS(PRC152,"AN/PRC-152");
SPATIALIZATION_SETTINGS(PRC148,"AN/PRC-148");
SPATIALIZATION_SETTINGS(PRC117F,"AN/PRC-117F");
SPATIALIZATION_SETTINGS(PRC77,"AN/PRC-77");
SPATIALIZATION_SETTINGS(SEM52SL,"SEM 52 SL");
SPATIALIZATION_SETTINGS(SEM70,"SEM 70");
SPATIALIZATION_SETTINGS(BF888S,"BF-888S");
SPATIALIZATION_SETTINGS(VRC64,"AN/VRC-64");
SPATIALIZATION_SETTINGS(VRC103,"AN/VRC-103");
SPATIALIZATION_SETTINGS(VRC110,"AN/VRC-110");
SPATIALIZATION_SETTINGS(VRC111,"AN/VRC-111");
SPATIALIZATION_SETTINGS(SEM90,"SEM90");

ADDON = true;
